name: "release web itch.io"
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:  
  release_web_itch:
    env:
      ITCH_USER: pxlpush
      ITCH_GAME: puzzle-puzzle
      BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
    runs-on: ubuntu-latest
    steps:
      - name: download Web artifact
        id: download-web-artifact
        uses: actions/download-artifact@v4
        with:
          name: web
      - name: deploy to itch.io (web)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: web.zip
          VERSION: ${{ github.sha }}
